export const SET_EATING_PLAN_DATE = "SET_EATING_PLAN_DATE";
export const CHANGE_EATING_PLAN_DATE = "CHANGE_EATING_PLAN_DATE";

export const ADD_EATING_PLAN_REQUEST = "ADD_EATING_PLAN_REQUEST";

export const EDIT_EATING_PLAN_REQUEST = "EDIT_EATING_PLAN_REQUEST";

export const GET_EATING_PLAN_REQUEST = "GET_EATING_PLAN_REQUEST";
export const GET_EATING_PLAN_SUCCESS = "GET_EATING_PLAN_SUCCESS ";

export const CLEAR_EATING_PLAN = "CLEAR_EATING_PLAN";
