export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";

export const LOGIN_USER_REQUST = "LOGIN_USER_REQUEST";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

export const LOGOUT_USER_ACTION = "LOGOUT_USER_ACTION";

export const EDIT_USER_PROFILE_REQUEST = "EDIT_USER_PROFILE_REQUEST";
export const EDIT_USER_PROFILE_SUCCESS = "EDIT_USER_PROFILE_SUCCESS";

export const EDIT_USER_AVATAR_REQUEST = "EDIT_USER_AVATAR_REQUEST";
export const EDIT_USER_AVATAR_SUCCESS = "EDIT_USER_AVATAR_SUCCESS";

export const SEND_NEW_VERIFICATION_MAIL = "SEND_NEW_VERIFICATION_MAIL";

export const SIGN_UP_WITH_GOOGLE_REQUEST = "SIGN_UP_WITH_GOOGLE_REQUEST";
export const SIGN_IN_WITH_GOOGLE_REQUEST = "SIGN_IN_WITH_GOOGLE_REQUEST";

export const SIGN_UP_WITH_FACEBOOK_REQUEST = "SIGN_UP_WITH_FACEBOOK_REQUEST";
export const SIGN_IN_WITH_FACEBOOK_REQUEST = "SIGN_IN_WITH_FACEBOOK_REQUEST";
