export const GET_EDAMAM_PRODUCTS_BY_NAME_REQUEST =
  "GET_EDAMAM_PRODUCTS_BY_NAME";
export const GET_EDAMAM_PRODUCTS_BY_NAME_SUCCESS =
  "GET_EDAMAM_PRODUCTS_BY_NAME_SUCCESS";

export const CLEAR_SUGGESTED_PRODUCTS = "CLEAR_SUGGESTED_PRODUCTS";

export const GET_USER_PRODUCTS_REQUEST = "GET_USER_PRODUCTS_REQUEST";
export const GET_USER_PRODUCTS_SUCCESS = "GET_USER_PRODUCTS_SUCCESS";

export const GET_PRODUCTS_BY_NAME_REQUEST = "GET_PRODUCTS_BY_NAME_REQUEST";
export const GET_PRODUCTS_BY_NAME_SUCCESS = "GET_PRODUCTS_BY_NAME_SUCCESS";

export const GET_PRODUCTS_BY_FILTERS_REQUEST =
  "GET_PRODUCTS_BY_FILTERS_REQUEST";
export const GET_PRODUCTS_BY_FILTERS_SUCCESS =
  "GET_PRODUCTS_BY_FILTERS_SUCCESS";

export const GET_SOME_PRODUCTS_REQUEST = "GET_SOME_PRODUCTS_REQUEST";
export const GET_SOME_PRODUCTS_SUCCESS = "GET_SOME_PRODUCTS_SUCCESS";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";

export const ADD_PRODUCT_BY_ID = "ADD_PRODUCT_BY_ID";

export const REMOVE_PRODUCT_FROM_USER_REQUEST =
  "REMOVE_PRODUCT_FROM_USER_REQUEST";

export const REMOVE_PRODUCT_REQUEST = "REMOVE_PRODUCT_REQUEST";

export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
