export const ADD_RECIPE_REQUEST = "ADD_RECIPE_REQUEST";

export const ADD_RECIPE_BY_ID_REQUEST = "ADD_RECIPE_BY_ID_REQUEST";

export const REMOVE_USER_RECIPE_REQUEST = "REMOVE_USER_RECIPE_REQUEST";

export const REMOVE_RECIPE_REQUEST = "REMOVE_RECIPE_REQUEST";

export const EDIT_RECIPE_REQUEST = "EDIT_RECIPE_REQUEST";

export const GET_RECIPES_BY_NAME_REQUEST = "GET_RECIPES_BY_NAME_REQUEST";
export const GET_RECIPES_BY_NAME_SUCCESS = "GET_RECIPES_BY_NAME_SUCCESS";

export const GET_RECIPES_BY_FILTERS_REQUEST = "GET_RECIPES_BY_FILTERS_REQUEST";
export const GET_RECIPES_BY_FILTERS_SUCCESS = "GET_RECIPES_BY_FILTERS_SUCCESS";

export const GET_USER_RECIPES_REQUEST = "GET_USER_RECIPES_REQUEST";
export const GET_USER_RECIPES_SUCCESS = "GET_USER_RECIPES_SUCCESS";

export const GET_SOME_RECIPES_REQUEST = "GET_SOME_RECIPES_REQUEST";
export const GET_SOME_RECIPES_SUCCESS = "GET_SOME_RECIPES_SUCCESS";

export const GET_RECIPE_REQUEST = "GET_RECIPE_REQUST";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";

export const CLEAR_RECIPES = "CLEAR_RECIPES";
